# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=$HOME/bin:/usr/local/bin:$PATH

source /opt/homebrew/opt/autoenv/activate.sh

# Go set up
export GOPATH="$HOME/src/go/"
export GOROOT="$(brew --prefix go)/libexec"
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Aliases
alias docker=podman
alias ll=ls -lah
alias python=/usr/local/bin/python3
alias pip=/usr/local/bin/pip3

# User configuration
export LANG=en_US.UTF-8
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
autoload -U +X bashcompinit && bashcompinit

# Bink keys
bindkey '[D' backward-word
bindkey '[C' forward-word
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"

# zsh plugins
source "${HOME}/.local/share/zinit/zinit.git/zinit.zsh"
# Zinit plugins configuration is now managed by Ansible

# Настройки zsh
setopt autocd
setopt correct
autoload -Uz compinit && compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
