---
- name: install Python versions
  homebrew:
    name:
      - python3
      - pypy
    state: present
  tags: python

- name: install uv
  homebrew:
    name:
      - uv
  tags: python

- name: Install OpenSSL for Python
  homebrew:
    name: openssl
    state: linked
  tags: python

- name: Add pip directory
  file:
    name: ~/.pip
    state: directory
  tags: python

- name: Install pip
  block:
    - name: Install pyp for Python 3
      command: python -m ensurepip --upgrade
  when: ansible_os_family == 'Darwin'
  tags:
    - python

- name: Setup pip configuration
  copy:
    dest: ~/.pip/pip.conf
    src: pip.conf
  tags: python
