---
- name: Install zsh
  homebrew: 
    name: zsh 
    state: latest
  when: ansible_os_family == 'Darwin'
  tags: zsh

- name: Add zsh to list of shells
  lineinfile:
    backup: yes
    dest: /etc/shells
    regexp: ^/usr/local/bin/zsh
    line: /usr/local/bin/zsh
  when: ansible_os_family == 'Darwin'
  become: true

- name: Change to zsh (Mac)
  shell: chsh -s /usr/local/bin/zsh {{ ansible_env.USER }}
  when: ansible_os_family == 'Darwin'

- name: Change to zsh (Ubuntu)
  shell: chsh -s /usr/bin/zsh {{ ansible_env.USER }}
  when: ansible_os_family == 'Ubuntu'

- name: Install zinit
  homebrew:
    name:
      - zinit
    state: latest
  when: ansible_os_family == 'Darwin'
  tags: zsh

- name: Update zinit
  shell: zinit self-update
  tags: zsh

- name: Add zshrc file
  copy: 
    src: zshrc 
    dest: ~/.zshrc
  tags: zsh
