---
- name: Install CLI tools
  homebrew: 
    name:
      - tree
      - wget
      - ack
      - autoenv
      - jq
      - fzf
    state: present
  when: ansible_os_family == 'Darwin'
  tags: utils

- name: Miscellany
  homebrew:
    name:
      - coreutils
    state: present
  when: ansible_os_family == 'Darwin'
  tags: utils
