---
- name: Install X-Code and tools (step 1)
  become: true
  command: /usr/sbin/softwareupdate --all --install --force --restart
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  async: 1000
  poll: 10
  register: xcode_install
  until: xcode_install.finished
  retries: 30
  delay: 10
  ignore_errors: true
  notify: xcode_install_status
  community.general.progress_bar:
    msg: "Installing X-Code and tools (step 1)... ({{ xcode_install.elapsed }}s)"
    total: 100
    current: "{{ (xcode_install.elapsed / 100) | int }}"

- name: Install X-Code and tools (step 2)
  become: true
  command: /usr/bin/xcode-select --install
  register: xcoderesult
  failed_when: "'FAILED' in xcoderesult.stderr"
  changed_when:
    - xcoderesult.rc == 0
    - '"command line tools are already installed" in xcoderesult.stderr'
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  async: 1000
  poll: 10
  until: xcoderesult.finished
  retries: 30
  delay: 10
  ignore_errors: true
  notify: xcode_install_status
  debug:
    msg: "Installing X-Code command line tools... ({{ xcoderesult.started | default(0) }}s)"
  interval: 10
  community.general.progress_bar:
    msg: "Installing X-Code and tools (step 2)... ({{ xcoderesult.elapsed }}s)"
    total: 100
    current: "{{ (xcoderesult.elapsed / 100) | int }}"

- name: Install Rosetta 2 for M1 processor
  command: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  register: rosetta
  failed_when:
    - rosetta.rc != 0
    - '"Installing Rosetta 2 on this system is not supported" not in rosetta.stdout'
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  community.general.progress_bar:
    msg: "Installing Rosetta 2... ({{ rosetta.elapsed }}s)"
    total: 100
    current: "{{ (rosetta.elapsed / 100) | int }}"

- name: Add desktop utility tools
  homebrew_cask:
    name:
      - dash
      - divvy
      - gpgtools
    state: present
  register: utility_tools
  ignore_errors: true
  failed_when:
    - '"Error:" in utility_tools.msg'
    - '"It seems there is already" not in utility_tools.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing desktop utility tools... ({{ utility_tools.elapsed }}s)"
    total: 100
    current: "{{ (utility_tools.elapsed / 100) | int }}"

- name: Add browsers
  homebrew_cask:
    name:
      - arc
      - firefox
      - google-chrome
    state: present
  register: browsers
  ignore_errors: true
  failed_when:
    - '"Error:" in browsers.msg'
    - '"It seems there is already" not in browsers.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing browsers... ({{ browsers.elapsed }}s)"
    total: 100
    current: "{{ (browsers.elapsed / 100) | int }}"

- name: Add development tools
  homebrew_cask:
    name:
      - visual-studio-code
      - warp
      - zed
      - intellij-goland-ce
      - postman
      - insomnia
    state: present
  register: development_tools
  ignore_errors: true
  failed_when:
    - '"Error:" in development_tools.msg'
    - '"It seems there is already" not in development_tools.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing development tools... ({{ development_tools.elapsed }}s)"
    total: 100
    current: "{{ (development_tools.elapsed / 100) | int }}"

- name: Add utilities
  homebrew_cask:
    name:
      - balenaetcher
      - caffeine
      - onyx
      - raycast
      - the-unarchiver
      - keka
      - omni-focus
      - telegram
      - whatsapp
    state: present
  register: utilities
  ignore_errors: true
  failed_when:
    - '"Error:" in utilities.msg'
    - '"It seems there is already" not in utilities.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing utilities... ({{ utilities.elapsed }}s)"
    total: 100
    current: "{{ (utilities.elapsed / 100) | int }}"

- name: Add productivity tools
  homebrew_cask:
    name:
      - obsidian
      - zoom
      - microsoft-office
    state: present
  register: productivity_tools
  ignore_errors: true
  failed_when:
    - '"Error:" in productivity_tools.msg'
    - '"It seems there is already" not in productivity_tools.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing productivity tools... ({{ productivity_tools.elapsed }}s)"
    total: 100
    current: "{{ (productivity_tools.elapsed / 100) | int }}"

- name: Add file sync tools
  homebrew_cask:
    name:
      - yandex-disk
    state: present
  register: file_sync_tools
  ignore_errors: true
  failed_when:
    - '"Error:" in file_sync_tools.msg'
    - '"It seems there is already" not in file_sync_tools.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing file sync tools... ({{ file_sync_tools.elapsed }}s)"
    total: 100
    current: "{{ (file_sync_tools.elapsed / 100) | int }}"

- name: Add media applications
  homebrew_cask:
    name:
      - vlc
      - handbrake
      - iina
    state: present
  register: media_applications
  ignore_errors: true
  failed_when:
    - '"Error:" in media_applications.msg'
    - '"It seems there is already" not in media_applications.msg'
  when: ansible_os_family == 'Darwin'
  tags: common
  community.general.progress_bar:
    msg: "Installing media applications... ({{ media_applications.elapsed }}s)"
    total: 100
    current: "{{ (media_applications.elapsed / 100) | int }}"

- name: Tap fonts' repo
  homebrew_tap: name=homebrew/cask-fonts
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  community.general.progress_bar:
    msg: "Tapping fonts' repo... ({{ homebrew_tap.elapsed }}s)"
    total: 100
    current: "{{ (homebrew_tap.elapsed / 100) | int }}"

- name: Install fonts
  homebrew_cask:
    name:
      - font-hack-nerd-font
      - font-fira-code
    state: present
  register: fonts
  ignore_errors: true
  failed_when:
    - '"Error:" in fonts.msg'
    - '"It seems there is already" not in fonts.msg'
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  community.general.progress_bar:
    msg: "Installing fonts... ({{ fonts.elapsed }}s)"
    total: 100
    current: "{{ (fonts.elapsed / 100) | int }}"

- name: Add screenshots directory
  vars:
    screenshot_dir: ~/Desktop/Screenshots
  register: screenshot_dir
  file:
      path: '{{ screenshot_dir }}'
      state: directory
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  community.general.progress_bar:
    msg: "Adding screenshots directory... ({{ screenshot_dir.elapsed }}s)"
    total: 100
    current: "{{ (screenshot_dir.elapsed / 100) | int }}"

- name: Set current screenshot directory
  command: "defaults write com.apple.screencapture location {{ screenshot_dir.path }}"
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos
  community.general.progress_bar:
    msg: "Setting current screenshot directory... ({{ command.elapsed }}s)"
    total: 100
    current: "{{ (command.elapsed / 100) | int }}"
